import { parseCSV, analyze } from './core.mjs';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
let source='', filename='', parsed=null, result=null, mapped=[];
const sample = (()=>{const lines=['timestamp,temperature_c,conductivity_ms_cm'];for(let i=0;i<96;i++){if(i>=43&&i<=49)continue;const t=new Date(Date.UTC(2026,0,1,0,i*30)).toISOString();const y=[22,23,65].includes(i)?'':i===78?'sensor reset':(16+1.8*Math.sin(i/11)+.42*Math.cos(i/3)).toFixed(3);lines.push(`${t},${y},${(42+.4*Math.sin(i/13)).toFixed(3)}`);}return lines.join('\n')+'\n';})();
function elem(tag, attrs={}, text){const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));if(text!==undefined)e.textContent=String(text);return e;}
function download(text,type,name){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function option(select,text,value){const o=document.createElement('option');o.value=String(value);o.textContent=text;select.append(o);}
function setError(message){parsed=null;$('error').textContent=message;$('error').hidden=false;result=null;mapped=[];$('chart').replaceChildren();$('chart').setAttribute('aria-label','No plot available.');$('chart-title').textContent='No plot available';$('x').replaceChildren();$('y').replaceChildren();$('summary').replaceChildren();$('issues').replaceChildren();$('readout').textContent='No plot to inspect.';$('issue-count').textContent='';$('issue-note').textContent='';$('marker-note').textContent='';for(const id of ['export-svg','export-report'])$(id).disabled=true;}
function parseSource(chooseColumns=false){try{const next=parseCSV(source,$('delimiter').value==='tab'?'\t':$('delimiter').value);if(next.headers.length<2)throw new Error('At least two columns are needed. Check the separator.');if(next.rows.length===0)throw new Error('The file has a header but no data records.');const oldX=$('x').value,oldY=$('y').value;parsed=next;$('x').replaceChildren();$('y').replaceChildren();next.headers.forEach((name,i)=>{const label=`${i+1}. ${name||'(unnamed column)'}`;option($('x'),label,i);option($('y'),label,i);});if(chooseColumns){const date=next.headers.findIndex(h=>/date|time/i.test(h));const x=date>=0?date:0;$('x').value=String(x);$('mode').value=date>=0?'date':'number';$('y').value=String(x===0?1:0);}else{$('x').value=Number(oldX)<next.headers.length?oldX:'0';$('y').value=Number(oldY)<next.headers.length?oldY:'1';}render();}catch(e){setError(e.message);}}
function load(text,name,separator=','){source=text;filename=name;$('filename').textContent=name;$('delimiter').value=separator;$('file-meta').textContent=`${new TextEncoder().encode(text).length.toLocaleString()} bytes`;parseSource(true);}
async function openFile(file){if(!file)return;if(file.size>5*1024*1024){setError('This file is over 5 MB. Open a smaller extract.');return;}try{const bytes=await file.arrayBuffer();const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);load(text,file.name,/\.tsv$/i.test(file.name)?'tab':',');}catch(e){setError(`Could not read this file as UTF-8: ${e.message}`);}}
function fmt(n){if(!Number.isFinite(n))return '—';const a=Math.abs(n);if(a!==0&&(a>=1e6||a<.001))return n.toExponential(2);return Number(n.toPrecision(5)).toLocaleString('en-US',{maximumFractionDigits:6});}
function scale(values,a,b){let low=Infinity,high=-Infinity;for(const v of values){if(v<low)low=v;if(v>high)high=v;}const magnitude=Math.max(Math.abs(low),Math.abs(high),1),lo=low/magnitude,hi=high/magnitude;return {low,high,at:v=>lo===hi?(a+b)/2:a+((v/magnitude-lo)/(hi-lo))*(b-a),tick:t=>(lo+(hi-lo)*t)*magnitude};}
function render(){if(!parsed)return;try{result=analyze(parsed.rows,{xColumn:Number($('x').value),yColumn:Number($('y').value),xMode:$('mode').value,gapFactor:$('gap').value==='off'?Infinity:Number($('gap').value),rowNumbers:parsed.rowNumbers});$('error').hidden=true;const allIssues=[...parsed.issues,...result.issues].sort((a,b)=>a.row-b.row);showIssues(allIssues);showStats(result.stats);draw();for(const id of ['export-svg','export-report'])$(id).disabled=false;}catch(e){setError(e.message);}}
function showStats(s){$('summary').replaceChildren();for(const[value,label]of[[s.rows,'data records'],[s.validPoints,'plotted points'],[s.missingY,'missing values'],[s.invalidX+s.invalidY,'invalid coordinates'],[s.gaps,'long gaps']]){const div=document.createElement('div');div.className='stat';const n=document.createElement('strong'),l=document.createElement('span');n.textContent=value.toLocaleString();l.textContent=label;div.append(n,l);$('summary').append(div);}}
function showIssues(issues){$('issues').replaceChildren();$('issue-count').textContent=issues.length?`${issues.length.toLocaleString()} ${issues.length===1?'observation':'observations'} to inspect`:'No parsing or plotting issues detected';const labels={ragged:'Column count',missingY:'Missing value',invalidX:'Invalid horizontal value',invalidY:'Invalid vertical value',duplicateX:'Repeated coordinate',outOfOrder:'Out of order',gap:'Long interval'};for(const issue of issues.slice(0,200)){const tr=document.createElement('tr');for(const value of [issue.row,labels[issue.kind]||issue.kind,issue.message]){const td=document.createElement('td');td.textContent=String(value);tr.append(td);}$('issues').append(tr);}if(!issues.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;td.textContent='The selected columns fit the parser and plotting rules. This does not establish scientific validity.';tr.append(td);$('issues').append(tr);}$('issue-note').textContent=issues.length>200?'Showing the first 200 observations. The exported report includes the full list.':'Record numbers refer to logical CSV records, including the header.';}
function draw(){const svg=$('chart');svg.replaceChildren();mapped=[];svg.append(elem('rect',{width:1040,height:500,fill:'#ffffff'}));const points=result.points.filter(p=>p.y!==null);const xname=parsed.headers[Number($('x').value)]||'X',yname=parsed.headers[Number($('y').value)]||'Y';$('chart-title').textContent=`${yname} / ${xname}`;$('readout').textContent='Move over the plot to inspect an observation.';$('marker-note').textContent=points.length>1200?'Point markers sampled; curve uses every valid point.':'';svg.setAttribute('aria-label',`${yname} by ${xname}. ${points.length} valid observations. Gaps remain unconnected.`);if(!points.length){svg.append(elem('text',{x:520,y:235,'text-anchor':'middle',fill:'#64646b','font-size':18,'font-family':'Helvetica,Arial,sans-serif'},'No valid coordinate pairs. Check the columns and data types.'));return;}const sx=scale(points.map(p=>p.x),80,1010),sy=scale(points.map(p=>p.y),425,35);for(let i=0;i<=5;i++){const t=i/5,y=425-390*t,x=80+930*t;svg.append(elem('line',{x1:80,x2:1010,y1:y,y2:y,stroke:'#e6e6e2','stroke-width':1}));svg.append(elem('text',{x:67,y:y+4,'text-anchor':'end',fill:'#64646b','font-size':11,'font-family':'Menlo,Consolas,monospace'},fmt(sy.tick(t))));const val=sx.tick(t),label=result.xMode==='date'?new Date(val).toISOString().replace('T',' ').slice(0,16):fmt(val);svg.append(elem('text',{x,y:449,'text-anchor':i===0?'start':i===5?'end':'middle',fill:'#64646b','font-size':11,'font-family':'Menlo,Consolas,monospace'},label));}svg.append(elem('line',{x1:80,x2:1010,y1:425,y2:425,stroke:'#171717'}));svg.append(elem('text',{x:545,y:482,'text-anchor':'middle',fill:'#171717','font-size':12,'font-family':'Helvetica,Arial,sans-serif'},xname+(result.xMode==='date'?' (UTC)':'')));for(const seg of result.segments){if(seg.length>1){const d=seg.map((p,i)=>`${i?'L':'M'}${sx.at(p.x).toFixed(2)},${sy.at(p.y).toFixed(2)}`).join(' ');svg.append(elem('path',{d,fill:'none',stroke:'#43358c','stroke-width':1.8,'stroke-linejoin':'round'}));}}const stride=Math.max(1,Math.ceil(points.length/1200));for(let i=0;i<points.length;i++){const p=points[i],cx=sx.at(p.x),cy=sy.at(p.y);mapped.push({p,cx,cy});if(i%stride===0)svg.append(elem('circle',{cx,cy,r:points.length>300?1.7:3,fill:'#43358c'}));}const focus=elem('circle',{id:'focus-point',r:5,fill:'#ee5c32',stroke:'white','stroke-width':2,visibility:'hidden'});svg.append(focus);}
$('chart').addEventListener('pointermove',e=>{if(!mapped.length)return;const box=$('chart').getBoundingClientRect(),px=(e.clientX-box.left)/box.width*1040,py=(e.clientY-box.top)/box.height*500;let nearest=null,best=Infinity;for(const m of mapped){const distance=(m.cx-px)**2+(m.cy-py)**2;if(distance<best){best=distance;nearest=m;}}if(!nearest)return;const focus=$('focus-point');focus.setAttribute('cx',nearest.cx);focus.setAttribute('cy',nearest.cy);focus.setAttribute('visibility','visible');const p=nearest.p;$('readout').textContent=`Record ${p.row}  |  ${result.xMode==='date'?new Date(p.x).toISOString():String(p.x)}  |  ${String(p.y)}`;});
$('file').addEventListener('change',e=>openFile(e.target.files[0]));$('demo').addEventListener('click',()=>load(sample,'Synthetic sensor sample.csv'));
$('delimiter').addEventListener('change',()=>parseSource(true));for(const id of ['x','y','mode','gap'])$(id).addEventListener('change',render);
$('export-svg').addEventListener('click',()=>{if(!result)return;const copy=$('chart').cloneNode(true);copy.querySelector('#focus-point')?.remove();copy.setAttribute('xmlns',NS);copy.setAttribute('width','1040');copy.setAttribute('height','500');const title=elem('title',{},`${filename}: ${$('chart-title').textContent}`);copy.prepend(title);download(new XMLSerializer().serializeToString(copy),'image/svg+xml','scope-plot.svg');});
$('export-report').addEventListener('click',()=>{if(!result)return;download(JSON.stringify({tool:'rowlet-scope',version:'0.1.0',source:filename,columns:{x:parsed.headers[Number($('x').value)],y:parsed.headers[Number($('y').value)],xMode:$('mode').value},gapFactor:$('gap').value==='off'?null:Number($('gap').value),stats:result.stats,issues:[...parsed.issues,...result.issues].sort((a,b)=>a.row-b.row),limits:'Parsing and plotting observations only. No imputation, sorting, scientific validation or independent verification.'},null,2)+'\n','application/json','scope-report.json');});
$('export-source').addEventListener('click',()=>download(source,'text/csv',filename.replace(/[^\w. -]/g,'_')));
let dragDepth=0;document.addEventListener('dragenter',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();dragDepth++;$('drop-overlay').hidden=false;}});document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});document.addEventListener('dragleave',()=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('drop-overlay').hidden=true;});document.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('drop-overlay').hidden=true;openFile(e.dataTransfer?.files[0]);});
load(sample,'Synthetic sensor sample.csv');
